apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    name: zookeeper
    app: broker
spec:
  containers:
  - name: zookeeper
    image: wurstmeister/zookeeper
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "512Mi"
        cpu: "150m"
      requests:
        memory: "150Mi"
        cpu: "50m"
    ports:
      - containerPort: 2181

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    name: zookeeper
  ports:
  - port: 2001
    targetPort: 2181

---

apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  containers:
  - name: kafka
    image: wurstmeister/kafka
    imagePullPolicy: IfNotPresent
    env:
      - name: KAFKA_ADVERTISED_HOST_NAME
        value: localhost
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: zookeeper-service:2001
    resources:
      limits:
        memory: "512Mi"
        cpu: "200m"
      requests:
        memory: "30Mi"
        cpu: "50m"
    ports:
      - containerPort: 9092

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    name: kafka
  ports:
  - port: 2002
    targetPort: 9092
