apiVersion: v1
kind: Pod
metadata:
  name: user-search
  labels:
    name: user-search
    app: user
spec:
  containers:
  - name: user-search
    image: user-search
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000

---

apiVersion: v1
kind: Pod
metadata:
  name: "user-elasticsearch"
  namespace: default
  labels:
    app: "user-elasticsearch"
spec:
  containers:
  - name: user-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: node.name
      value: user01        
    ports:
    - containerPort:  9200
      name:  http 
  restartPolicy: Always